---
- name: Set up local machine
  hosts: localhost
  connection: local

  tasks:
  - debug: msg="{{ lookup('env','USER') }}"
  - name: install packages
    package:
      name:
      - htop
      - tmux

  - name: copy file
    copy:
      src: files/something.txt
      dest: /home/roman/test/ansible-something.txt
      owner: root
      group: root
