---
- hosts: localhost
  connection: local
  become: true
  become_user: roman
  become_method: sudo

  tasks:
  - debug: msg="{{ lookup('env','USER') }}"
  - name: install packages
    package:
      name:
      - htop
      - tmux

  - name: copy file
    copy:
      src: files/something.txt
      dest: /home/roman/test/ansible-something.txt
      owner: root
      group: root
